test:
    adapter: <%= ENV['WERCKER_POSTGRESQL_ADAPTER'] || 'postgresql' %>
    encoding: "utf8"
    database: <%= ENV['POSTGRES_ENV_POSTGRES_DB'] || ENV['POSTGRES_ENV_POSTGRES_USER'] || 'postgres' %><%= ENV['TEST_ENV_NUMBER'] %>
    username: <%= ENV['POSTGRES_ENV_POSTGRES_USER'] || 'postgres' %>
    password: <%= ENV['POSTGRES_ENV_POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
    port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
    min_messages: warning
